name: C Project Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"

jobs:
  build:
    # if: github.repository == 'crispy-cookie/xdotool-deb'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxtst-dev \
            libxi-dev \
            libxkbcommon-dev \
            libxinerama-dev \
            checkinstall \
            build-essential

      - name: Build Project
        run: make

      - name: Create Package with checkinstall
        run: |
          VERSION="v4.$(date +'%Y%m%d')"
          sudo checkinstall --fstrans=no --install=no --nodoc  --pkgname="xdotool" --pkgversion="4.$(date +'%Y%m%d')"

      - name: Upload Artifact for Releasea
        uses: actions/upload-artifact@v7
        with:
          name: xdotool
          # path: /home/runner/work/xdotool-deb/xdotool-deb/xdotool_20260614-1_amd64.deb
          path: /home/runner/work/xdotool-deb/xdotool-deb/xdotool_*_amd64.deb
          archive: false
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        # if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1.21.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "/home/runner/work/xdotool-deb/xdotool-deb/xdotool_*_amd64.deb"
          tag: ${{ github.ref_name }}-${{ github.sha }}
          commit: ${{ github.sha }}
          artifactErrorsFailBuild: true
          makeLatest: true
